## Annotated Docker Image Configuration
## Full VEP pipeline with pre-annotated gnomAD cache

## * REQUIRED RESOURCES *
annotation_tool_cmd: "vep"
tool_version_command: "vep --version | head -1 | awk '{print $2}'"
bcftools_cmd: "${VCFSTASH_ROOT}/tools/bcftools"
reference: "/tmp/dummy.fa"  # Placeholder - not used during cache init from BCF
chr_add: "${VCFSTASH_ROOT}/resources/chr_add.txt"
temp_dir: "/tmp"

## * VEP CONFIGURATION *
vep_buffer: 500000
vep_forks: 8
vep_cache: "/opt/vep/.vep"  # VEP cache location in container

## * OPTIONAL CHECKS *
optional_checks:
  genome_build: "GRCh38"
  vep_cache_version: "115"
