## * REQUIRED RESOURCES *
annotation_tool_cmd: "vep"
tool_version_command: "vep --version | head -1 | awk '{print $2}'"
bcftools_cmd: "${VCFSTASH_ROOT}/tools/bcftools"
chr_add: "${VCFSTASH_ROOT}/resources/chr_add.txt"
temp_dir: "/tmp"

## * OPTIONAL RESOURCES *
vep_buffer: 500000
vep_forks: 8
vep_cache: "/vep_data/115.2"

## * OPTIONAL CHECKS *
optional_checks:
  vep_cache_version: "115.2"
